name: buddy-copilot
base: core24
version: '0.1'
summary: Buddy-OS copilot tray UI
description: |
  Tray-style Buddy Copilot UI with always-visible input.

grade: devel
confinement: classic

apps:
  buddy-copilot:
    command: bin/buddy-copilot

parts:
  buddy-copilot:
    plugin: dump
    source: ../../../snaps/_src/buddy-copilot
    stage:
      - bin/buddy-copilot
