name: buddy-gadget
base: core24
version: '0.1'
summary: Buddy-OS gadget snap
description: |
  Gadget snap defining partitions, boot assets, and grub layout
  for Buddy-OS (Ubuntu Core 24.04.3 classic).

grade: devel
confinement: strict
type: gadget

parts:
  gadget:
    plugin: dump
    source: .
    stage:
      - gadget.yaml
