FROM docker.io/snapcore/snapcraft:stable

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl wget git jq \
    xorriso squashfs-tools \
    mtools dosfstools \
    qemu-utils parted e2fsprogs \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
CMD ["bash"]
