name: buddy-settings
base: core24
version: '0.1'
summary: Buddy-OS settings UI
description: |
  COSMIC settings integration for Buddy AI.

grade: devel
confinement: classic

apps:
  buddy-settings:
    command: bin/buddy-settings

parts:
  buddy-settings:
    plugin: dump
    source: ../../../snaps/_src/buddy-settings
    stage:
      - bin/buddy-settings
